### ISSUE TITLE
Search/filter features

### ISSUE THREAD

**Issue by unmick** [Memurame/grav-theme-traveler#4]
Hello,

First, good job !

Do you have in mind to add the possibility to search a key word inside the content/title  or filter per date?

It's ok for the taxonomy .

Thanks

**Comment by Memurame** [comment]
Hi.
Thanks.

A search function I have planned to search in the title. Comes with the next update.

**Comment by Memurame** [comment]
You can now use the plugin Simplesearch.
Install the plugin and then it should work.

Could I fulfill your wish?

**Comment by unmick** [comment]
Perfect :-)
I have added in the frontmatter of the blog.md:
`simplesearch:
    route: '@self'
    filters:
        - '@self'
        -
            '@taxonomy':
                - tag
        -
            filter_combinator: and`
