### ISSUE TITLE
Navigation and number of pages

### ISSUE THREAD

**Issue by unmick** [Memurame/grav-theme-traveler#6]
Hello,
Just a comment....
If you have got couple of pages, your navigation between the pages is not great....
![image](https://user-images.githubusercontent.com/35163557/69891012-a1dd1a00-12f9-11ea-807e-89e1614d1697.png)

**Comment by Memurame** [comment]
Thx, i will fix this in next update.

**Comment by Memurame** [comment]
The problem should now be resolved.
Now the colors of the page can be changed directly in the theme settings.
